language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-format-5.0

script:
  - env | grep "^TRAVIS_"
  - ./clang-format-check -r .
